namespace ZedSharp.Models.Matches
{
    public class ParticipantStats
    {
        public int PhysicalDamageDealt { get; set; }
        public int NeutralMinionsKilledTeamJungle { get; set; }
        public int MagicDamageDealt { get; set; }
        public int TotalPlayerScore { get; set; }
        public int Deaths { get; set; }
        public bool Win { get; set; }
        public int NeutralMinionsKilledEnemyJungle { get; set; }
        public int AltarsCaptured { get; set; }
        public int LargestCriticalStrike { get; set; }
        public int TotalDamageDealt { get; set; }
        public int MagicDamageDealtToChampions { get; set; }
        public int VisionWardsBoughtInGame { get; set; }
        public int DamageDealtToObjectives { get; set; }
        public int LargestKillingSpree { get; set; }
        public int Item1 { get; set; }
        public int QuadraKills { get; set; }
        public int TeamObjective { get; set; }
        public int TotalTimeCrowdControlDealt { get; set; }
        public int IntestTimeSpentLiving { get; set; }
        public int WardsKilled { get; set; }
        public bool FirstTowerAssist { get; set; }
        public bool FirstTowerKill { get; set; }
        public int Item2 { get; set; }
        public int Item3 { get; set; }
        public int Item0 { get; set; }
        public bool FirstBloodAssist { get; set; }
        public int VisionScore { get; set; }
        public int WardsPlaced { get; set; }
        public int Item4 { get; set; }
        public int Item5 { get; set; }
        public int Item6 { get; set; }
        public int TurretKills { get; set; }
        public int TripleKills { get; set; }
        public int DamageSelfMitigated { get; set; }
        public int ChampLevel { get; set; }
        public int NodeNeutralizeAssist { get; set; }
        public bool FirstInhibitorKill { get; set; }
        public int GoldEarned { get; set; }
        public int MagicalDamageTaken { get; set; }
        public int Kills { get; set; }
        public int DoubleKills { get; set; }
        public int NodeCaptureAssist { get; set; }
        public int TrueDamageTaken { get; set; }
        public int NodeNeutralize { get; set; }
        public bool FirstInhibitorAssist { get; set; }
        public int Assists { get; set; }
        public int UnrealKills { get; set; }
        public int NeutralMinionsKilled { get; set; }
        public int ObjectivePlayerScore { get; set; }
        public int CombatPlayerScore { get; set; }
        public int DamageDealtToTurrets { get; set; }
        public int AltarsNeutralized { get; set; }
        public int PhysicalDamageDealtToChampions { get; set; }
        public int GoldSpent { get; set; }
        public int TrueDamageDealt { get; set; }
        public int TrueDamageDealtToChampions { get; set; }
        public int ParticipantId { get; set; }
        public int PentaKills { get; set; }
        public int TotalHeal { get; set; }
        public int TotalMinionsKilled { get; set; }
        public bool FirstBloodKill { get; set; }
        public int NodeCapture { get; set; }
        public int LargestMultiKill { get; set; }
        public int SightWardsBoughtInGame { get; set; }
        public int TotalDamageDealtToChampions { get; set; }
        public int TotalUnitsHealed { get; set; }
        public int InhibitorKills { get; set; }
        public int TotalScoreRank { get; set; }
        public int TotalDamageTaken { get; set; }
        public int KillingSprees { get; set; }
        public int TimeCCingOthers { get; set; }
        public int PhysicalDamageTaken { get; set; }
    }
}